### ISSUE TITLE
JSON Endpoint

### ISSUE THREAD

**Issue by kernelsmith** [jwalker/zdi_advisory_explorer#3]
Hey @jwalker ,

There's a little known JSON endpoint at https://www.zerodayinitiative.com/api/advisories/published/. It has more info than the RSS feed, but it's still by year, like https://www.zerodayinitiative.com/api/advisories/published/?year=2023, but you could get all vulns in 9 queries, and you'd probably only need to check the current year for anything new, except around the new year. I "know a guy" if you want to know more. If so, hit me up at my `$github.username at $github.username dot you know what` email

**Comment by jwalker** [comment]
Thanks @kernelsmith for the useful information and apologies for the delayed change. As you may see from the recent PR I added the new changes to only rely on data from the JSON API now. HUGE THANK YOU. This will definitely be more impactful for target application analysis or simply early application threat modeling when choosing software for vulnerability discovery and research. 

I would definitely be interested in learning more about getting all the vulns in those 9 API calls/queries :P. Ill send over an email.
